name: Astronomy Engine Unit Tests
on: [push]
jobs:
  Astronomy-Engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, windows-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to path
      if: startsWith(matrix.os, 'windows')
      uses: microsoft/setup-msbuild@v1.1
    - name: Init dotnet core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Init Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install Python tools
      run: python -m pip install --upgrade pip && pip install pylint mypy
    - name: Install documentation tools Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt install -y doxygen xsltproc cppcheck
    - name: Install documentation tools macOS
      if: startsWith(matrix.os, 'macOS')
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install doxygen cppcheck
    - name: Init Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: gradle/wrapper-validation-action@v1

    - name: Test Astronomy Engine Unix
      if: startsWith(matrix.os, 'windows') == false
      run: generate/commit_hook

    - name: Test Astronomy Engine Windows
      if: startsWith(matrix.os, 'windows')
      shell: cmd
      run: call generate\commit_hook.bat
