name: Astronomy Engine Unit Tests
on: [push]
jobs:
  Astronomy-Engine-Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Init Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python linter
      run: python -m pip install --upgrade pip && pip install pylint
    - name: Install documentation tools
      run: sudo apt install -y doxygen xsltproc
    - name: Init Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Test Astronomy Engine
      run: cd generate && rm -f output/vsop*.txt output/*.eph output/jupiter_moons.txt && ./run && ./verify_clean

  Astronomy-Engine-Macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Init dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Init Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python linter
      run: python -m pip install --upgrade pip && pip install pylint
    - name: Install documentation tools
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install doxygen
    - name: Init Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Test Astronomy Engine
      run: cd generate && rm -f output/vsop*.txt output/*.eph output/jupiter_moons.txt && ./run && ./verify_clean

  Astronomy-Engine-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    - name: Init dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Init Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python linter
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install documentation tools
      shell: cmd
      run: |
        md bin
        cd bin
        curl -o doxygen.zip https://www.doxygen.nl/files/doxygen-1.9.3.windows.x64.bin.zip
        7z x doxygen.zip
        del doxygen.zip
        cd ..
    - name: Init Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Test Astronomy Engine
      shell: cmd
      run: |
        cd generate
        del output\vsop*.txt output\*.eph output\jupiter_moons.txt
        run.bat
        verify_clean.bat
